// scripts/src/arb_merge.dart — pure logic behind scripts/gen_l10n_arb.dart.
//
// No dart:io here so the root test/ suite can exercise every rule in memory.
//
// Stage 1 (merge): `app/lib/l10n/parts/<feature>_<lang>.arb` → one map per
// language. Stage 2 (identifier): dotted `screen.element.state` keys
// (01 §1 rule 9 🔒) → Dart identifiers for gen_l10n (`app.name` → `appName`).
import 'dart:convert';

/// Languages every feature must ship (01 §1 rule 1, CLAUDE.md rule 8).
const languages = ['en', 'pa', 'hi'];

/// Marker written into the merged `app_<lang>.arb` files.
const generatedMarker = '@@x-generated';
const generatedNote =
    'GENERATED by scripts/gen_l10n_arb.dart from app/lib/l10n/parts/ — '
    'edit <feature>_<lang>.arb there, never this file.';

/// A rule violation with a message that names the offending part file.
class ArbError implements Exception {
  ArbError(this.message);
  final String message;
  @override
  String toString() => message;
}

/// One `<feature>_<lang>.arb` file, already read from disk.
class ArbPart {
  ArbPart({required this.path, required this.text});

  /// Path as it should appear in error messages.
  final String path;
  final String text;

  static final _name = RegExp(r'^(.+)_([a-z]{2})\.arb$');

  String get _basename => path.split('/').last;

  /// `parts/home_pa.arb` → `home`; throws when the name is not
  /// `<feature>_<lang>.arb`.
  String get feature => _match.group(1)!;

  /// `parts/home_pa.arb` → `pa`.
  String get lang => _match.group(2)!;

  RegExpMatch get _match {
    final m = _name.firstMatch(_basename);
    if (m == null) {
      throw ArbError('$path: part files are named <feature>_<lang>.arb');
    }
    return m;
  }
}

/// Parses one ARB document and validates its shape.
///
/// Rules: a JSON object; `@@locale` (if present) equals [lang]; no other
/// `@@` attribute; every non-`@` value is a String; every `@key` value is an
/// object whose `key` exists in the same file.
Map<String, Object?> parseArb(String path, String text, {String? lang}) {
  Object? decoded;
  try {
    decoded = jsonDecode(text);
  } on FormatException catch (e) {
    throw ArbError('$path: malformed ARB — ${e.message}');
  }
  if (decoded is! Map<String, Object?>) {
    throw ArbError('$path: malformed ARB — top level must be a JSON object');
  }
  for (final e in decoded.entries) {
    final k = e.key;
    if (k == '@@locale') {
      if (lang != null && e.value != lang) {
        throw ArbError('$path: @@locale must be "$lang" (got "${e.value}")');
      }
    } else if (k.startsWith('@@')) {
      throw ArbError('$path: unexpected attribute "$k" (only @@locale)');
    } else if (k.startsWith('@')) {
      if (e.value is! Map) {
        throw ArbError('$path: "$k" metadata must be an object');
      }
      if (!decoded.containsKey(k.substring(1))) {
        throw ArbError('$path: "$k" has no matching "${k.substring(1)}"');
      }
    } else if (e.value is! String) {
      throw ArbError('$path: "$k" must be a string');
    }
  }
  return decoded;
}

/// Result of [mergeParts]: one ordered ARB map per language plus the
/// key → part-file index that check_strings uses to blame a file.
class MergeResult {
  MergeResult(this.byLanguage, this.owner);

  /// `{'en': {...}, 'pa': {...}, 'hi': {...}}` — each carries `@@locale`,
  /// [generatedMarker], then keys sorted, each followed by its `@key` meta.
  final Map<String, Map<String, Object?>> byLanguage;

  /// `{'en': {'app.name': 'parts/core_en.arb', ...}, ...}`.
  final Map<String, Map<String, String>> owner;
}

/// Merges [parts] (every `<feature>_<lang>.arb` in the parts directory).
///
/// Throws [ArbError] on: a malformed file; a key present in two features;
/// a key present in one language of a feature but not the others (including
/// a feature that lacks a language file altogether).
MergeResult mergeParts(Iterable<ArbPart> parts) {
  final byFeature = <String, Map<String, Map<String, Object?>>>{};
  final pathOf = <String, Map<String, String>>{}; // feature → lang → path
  for (final p in parts) {
    final feature = p.feature;
    final lang = p.lang;
    if (!languages.contains(lang)) {
      throw ArbError('${p.path}: language "$lang" is not one of $languages');
    }
    final prior = pathOf[feature]?[lang];
    if (prior != null) {
      throw ArbError('${p.path} and $prior both claim $feature/$lang');
    }
    (pathOf[feature] ??= {})[lang] = p.path;
    (byFeature[feature] ??= {})[lang] = parseArb(p.path, p.text, lang: lang);
  }

  final merged = {
    for (final l in languages)
      l: <String, Object?>{'@@locale': l, generatedMarker: generatedNote},
  };
  final owner = {for (final l in languages) l: <String, String>{}};
  final keyFeature = <String, String>{}; // key → feature (duplicate check)

  final features = byFeature.keys.toList()..sort();
  for (final feature in features) {
    final langs = byFeature[feature]!;
    final paths = pathOf[feature]!;
    for (final l in languages) {
      if (!langs.containsKey(l)) {
        throw ArbError(
          'feature "$feature" has ${paths.values.join(', ')} but no '
          '${feature}_$l.arb — every feature ships en, pa and hi',
        );
      }
    }
    final union = <String>{
      for (final m in langs.values)
        for (final k in m.keys)
          if (!k.startsWith('@')) k,
    }.toList()..sort();
    for (final key in union) {
      for (final l in languages) {
        if (!langs[l]!.containsKey(key)) {
          throw ArbError(
            '"$key": in ${paths[_firstLangWith(langs, key)]} '
            'but missing from ${paths[l]}',
          );
        }
      }
      final otherFeature = keyFeature[key];
      if (otherFeature != null) {
        throw ArbError(
          '"$key": defined in both ${pathOf[otherFeature]!['en']} '
          'and ${paths['en']} — one key, one part',
        );
      }
      keyFeature[key] = feature;
    }
  }

  final allKeys = keyFeature.keys.toList()..sort();
  for (final key in allKeys) {
    final feature = keyFeature[key]!;
    for (final l in languages) {
      final src = byFeature[feature]![l]!;
      merged[l]![key] = src[key];
      if (src.containsKey('@$key')) merged[l]!['@$key'] = src['@$key'];
      owner[l]![key] = pathOf[feature]![l]!;
    }
  }
  return MergeResult(merged, owner);
}

String _firstLangWith(Map<String, Map<String, Object?>> langs, String key) =>
    languages.firstWhere((l) => langs[l]?.containsKey(key) ?? false);

/// Stage 2: dotted keys → identifier keys. `@@` attributes are copied except
/// [generatedMarker] (gen_l10n does not need it). Two dotted keys mapping to
/// one identifier is an error.
Map<String, Object?> toIdentifierArb(String path, Map<String, Object?> src) {
  final out = <String, Object?>{};
  final seen = <String, String>{};
  for (final e in src.entries) {
    if (e.key == generatedMarker) continue;
    if (e.key.startsWith('@@')) {
      out[e.key] = e.value;
      continue;
    }
    final meta = e.key.startsWith('@');
    final dotted = meta ? e.key.substring(1) : e.key;
    final id = identifier(dotted);
    final prior = seen[id];
    if (prior != null && prior != dotted) {
      throw ArbError('$path: "$dotted" and "$prior" both map to "$id"');
    }
    seen[id] = dotted;
    out[meta ? '@$id' : id] = e.value;
  }
  return out;
}

/// `home.money_in.label` → `homeMoneyInLabel`.
String identifier(String dotted) {
  final parts = dotted
      .split(RegExp(r'[._-]'))
      .where((p) => p.isNotEmpty)
      .toList();
  if (parts.isEmpty) throw ArbError('key "$dotted" is empty');
  final b = StringBuffer(parts.first.toLowerCase());
  for (final p in parts.skip(1)) {
    b.write(p[0].toUpperCase());
    b.write(p.substring(1));
  }
  final id = b.toString();
  if (!RegExp(r'^[a-z][A-Za-z0-9]*$').hasMatch(id)) {
    throw ArbError('key "$dotted" cannot become a Dart identifier');
  }
  return id;
}

/// Stable, diff-friendly JSON for generated ARB files.
String encodeArb(Map<String, Object?> m) =>
    '${const JsonEncoder.withIndent('  ').convert(m)}\n';
