// scripts/gen_tokens.dart — the ONLY writer of tokens.dart / tokens.css.
//
// design/tokens/tokens.json is the single source for token values (CLAUDE.md
// § Precedence 2). This script renders it into
//   design/tokens/tokens.css      (mockups / HTML canvases)
//   design/tokens/tokens.dart     (reference copy, design/)
//   app/lib/shared/tokens.dart    (the copy the app imports)
//
//   dart run scripts/gen_tokens.dart          # write
//   dart run scripts/gen_tokens.dart --check  # exit 1 if any output would change (CI)
//
// Never edit the outputs by hand. Add a value to tokens.json, re-run.
import 'dart:convert';
import 'dart:io';

const _json = 'design/tokens/tokens.json';
const _outputs = <String, String Function(Map<String, dynamic>)>{
  'design/tokens/tokens.css': _css,
  'design/tokens/tokens.dart': _dart,
  'app/lib/shared/tokens.dart': _dart,
};

Future<void> main(List<String> args) async {
  final check = args.contains('--check');
  final tokens =
      jsonDecode(File(_json).readAsStringSync()) as Map<String, dynamic>;
  var drift = false;
  for (final entry in _outputs.entries) {
    var body = entry.value(tokens);
    if (entry.key.endsWith('.dart')) body = await _dartFormat(body);
    final file = File(entry.key);
    final current = file.existsSync() ? file.readAsStringSync() : null;
    if (current == body) continue;
    if (check) {
      stderr.writeln(
        'DRIFT: ${entry.key} does not match tokens.json — run `dart run scripts/gen_tokens.dart`',
      );
      drift = true;
    } else {
      file.createSync(recursive: true);
      file.writeAsStringSync(body);
      stdout.writeln('wrote ${entry.key}');
    }
  }
  if (drift) exit(1);
}

Future<String> _dartFormat(String src) async {
  final tmp = File('${Directory.systemTemp.path}/rk_tokens_$pid.dart')
    ..writeAsStringSync(src);
  try {
    final r = await Process.run('dart', ['format', tmp.path]);
    if (r.exitCode != 0) throw StateError('dart format failed: ${r.stderr}');
    return tmp.readAsStringSync();
  } finally {
    tmp.deleteSync();
  }
}

// ---------------------------------------------------------------- helpers

String _meta(Map<String, dynamic> t) {
  final m = t[r'$meta'] as Map<String, dynamic>;
  return 'tokens.json v${m['version']}; ${m['source']}';
}

String _camel(String kebab) {
  final parts = kebab.split('-');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

/// `#RRGGBB` or `rgba(r,g,b,a)` → `0xAARRGGBB`.
String _argb(String v) {
  if (v.startsWith('#')) return '0xFF${v.substring(1).toUpperCase()}';
  final m = RegExp(r'rgba\((\d+),(\d+),(\d+),([\d.]+)\)')
      .firstMatch(v.replaceAll(' ', ''));
  if (m == null) throw FormatException('unsupported colour "$v"');
  String hex(num n) =>
      n.round().toRadixString(16).padLeft(2, '0').toUpperCase();
  final a = (double.parse(m[4]!) * 255).round();
  return '0x${hex(a)}${hex(int.parse(m[1]!))}${hex(int.parse(m[2]!))}${hex(int.parse(m[3]!))}';
}

String _ms(num ms) => ms % 1000 == 0 ? '${ms ~/ 1000}s' : '${ms}ms';

Map<String, dynamic> _m(Object? o) => o as Map<String, dynamic>;

// ---------------------------------------------------------------- Dart

String _dart(Map<String, dynamic> t) {
  final b = StringBuffer()
    ..writeln('// GENERATED by scripts/gen_tokens.dart from ${_meta(t)}.')
    ..writeln(
      '// Do not edit — change design/tokens/tokens.json and re-run. CI fails on drift.',
    )
    ..writeln('//')
    ..writeln(
      '// UI code uses these tokens ONLY; a hex literal in a widget is review-blocking',
    )
    ..writeln('// (CLAUDE.md § Layout). Never imported by core packages.')
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln();

  final color = _m(t['color']);
  for (final mode in (_m(t[r'$meta'])['modes'] as List).cast<String>()) {
    final cls = 'RkColors${mode[0].toUpperCase()}${mode.substring(1)}';
    b.writeln(
      '/// Colours — $mode. Light and dark are full sets; the app never derives one from the other.',
    );
    b.writeln('abstract final class $cls {');
    for (final e in _m(color[mode]).entries) {
      final role = (_m(e.value)['role'] as String).trim();
      if (role.isNotEmpty) b.writeln('  /// $role');
      b.writeln(
        '  static const ${_camel(e.key)} = Color(${_argb(_m(e.value)['value'] as String)});',
      );
    }
    b.writeln('}\n');
  }

  final typo = _m(t['typography']);
  final lh = _m(typo['lineHeight']);
  b
    ..writeln(
      '/// Type scale — logical px at scale 1.0; layouts must survive OS font scale 200 % (07 §18).',
    )
    ..writeln('/// ${_m(typo['family'])['note']}')
    ..writeln('/// ${_m(typo['numerals'])['rule']}')
    ..writeln('abstract final class RkType {')
    ..writeln("  static const family = 'Mukta';")
    ..writeln("  static const familyGurmukhi = 'MuktaMahee';")
    ..writeln("  static const familyFallback = 'NotoSans';")
    ..writeln('  static const lineHeightTight = ${lh['tight']};')
    ..writeln('  static const lineHeightNormal = ${lh['normal']};')
    ..writeln()
    ..writeln('  /// Amounts: ALWAYS tabular figures (11 §4.4).')
    ..writeln('  static const tabular = [FontFeature.tabularFigures()];')
    ..writeln();
  for (final e in _m(typo['scale']).entries) {
    final s = _m(e.value);
    final isAmount = e.key.startsWith('amount-');
    final size = s['size'] as num;
    // Generator rule: headings (≥ 20) take the tight line height, running text the normal one;
    // amounts carry tabular figures and no fixed height (they sit in rows sized by content).
    final extra = isAmount
        ? 'fontFeatures: tabular'
        : 'height: ${size >= 20 ? lh['tight'] : lh['normal']}';
    if (s['note'] != null) b.writeln('  /// ${s['note']}');
    b.writeln(
      '  static const ${_camel(e.key)} = TextStyle(fontSize: $size, fontWeight: FontWeight.w${s['weight']}, $extra);',
    );
  }
  b.writeln('}\n');

  final space = _m(t['space']);
  final unit = space['unit'] as int;
  b
    ..writeln('/// ${space['note']}')
    ..writeln('abstract final class RkSpace {');
  for (final step in (space['steps'] as List).cast<int>()) {
    b.writeln('  static const s${step ~/ unit} = ${step.toDouble()};');
  }
  b
    ..writeln('  static const gutter = ${(space['gutter'] as num).toDouble()};')
    ..writeln(
      '  static const cardPadding = ${(space['cardPadding'] as num).toDouble()};',
    )
    ..writeln(
      '  static const rowMinHeight = ${(space['rowMinHeight'] as num).toDouble()};',
    )
    ..writeln('}\n');

  final radius = _m(t['radius']);
  b
    ..writeln('abstract final class RkRadius {')
    ..writeln('  static const sm = ${(radius['sm'] as num).toDouble()};')
    ..writeln('  static const md = ${(radius['md'] as num).toDouble()};')
    ..writeln('  static const lg = ${(radius['lg'] as num).toDouble()};')
    ..writeln('  /// ${_m(radius['ruleLeft'])['note']}')
    ..writeln(
      '  static const ruleLeftWidth = ${(_m(radius['ruleLeft'])['width'] as num).toDouble()};',
    )
    ..writeln('}\n');

  final motion = _m(t['motion']);
  String cubic(String s) {
    final n = RegExp(r'cubic-bezier\(([^)]*)\)')
        .firstMatch(s)!
        .group(1)!
        .split(',')
        .map((x) => double.parse(x.trim()))
        .toList();
    return 'Cubic(${n[0]}, ${n[1]}, ${n[2]}, ${n[3]})';
  }

  final dur = _m(motion['duration']);
  final unlock = _m(motion['mark-unlock']);
  final shake = _m(motion['mark-fail-shake']);
  final loader = _m(motion['loader']);
  final skel = _m(motion['skeleton']);
  final splash = _m(motion['splash']);
  b
    ..writeln('/// ${_m(t['elevation'])['rule']}.')
    ..writeln('abstract final class RkMotion {')
    ..writeln(
      '  static const easeBrand = ${cubic(motion['ease-brand'] as String)};',
    )
    ..writeln(
      '  static const easeEntries = ${cubic(motion['ease-entries'] as String)};',
    );
  for (final e in dur.entries) {
    b.writeln('  static const ${e.key} = Duration(milliseconds: ${e.value});');
  }
  b
    ..writeln()
    ..writeln('  /// ${unlock['note']}')
    ..writeln(
      '  static const markUnlockTotal = Duration(milliseconds: ${unlock['total-ms']});',
    )
    ..writeln(
      '  static const markSplashMultiplier = ${unlock['multiplier-splash']};',
    )
    ..writeln(
      '  static const markBiometricMultiplier = ${unlock['multiplier-biometric']};',
    )
    ..writeln()
    ..writeln('  /// ${shake['note']}')
    ..writeln(
      '  static const failShake = Duration(milliseconds: ${shake['duration-ms']});',
    )
    ..writeln(
      '  static const failShakeAmplitudeUnits = ${(shake['amplitude-units'] as num).toDouble()};',
    )
    ..writeln('  static const failShakeCycles = ${shake['cycles']};')
    ..writeln()
    ..writeln('  /// ${loader['note']}')
    ..writeln('  /// Copy: ${loader['copy']}')
    ..writeln(
      '  static const loaderTrackHeight = ${(loader['track-height'] as num).toDouble()};',
    )
    ..writeln(
      '  static const loaderSegmentFraction = ${loader['segment-fraction']};',
    )
    ..writeln(
      '  static const loaderSweep = Duration(milliseconds: ${loader['loop-sweep-ms']});',
    )
    ..writeln(
      '  static const loaderAppearDelay = Duration(milliseconds: ${loader['appear-delay-ms']});',
    )
    ..writeln(
      '  static const loaderEscalate = Duration(milliseconds: ${loader['escalate-ms']});',
    )
    ..writeln()
    ..writeln('  /// ${skel['note']}')
    ..writeln('  static const skeletonStatic = ${skel['static']};')
    ..writeln(
      '  static const skeletonLabelWidthMin = ${skel['label-width-min']};',
    )
    ..writeln(
      '  static const skeletonLabelWidthMax = ${skel['label-width-max']};',
    )
    ..writeln()
    ..writeln('  /// ${splash['note']}')
    ..writeln(
      '  static const splashSlowStart = Duration(milliseconds: ${splash['slow-start-threshold-ms']});',
    )
    ..writeln('}\n');

  final icon = _m(t['iconography']);
  final mark = _m(icon['mark']);
  b
    ..writeln('/// ${icon['note']}. Mark: ${mark['rule']}.')
    ..writeln('abstract final class RkIcon {')
    ..writeln('  static const grid = ${(icon['grid'] as num).toDouble()};')
    ..writeln('  static const stroke = ${(icon['stroke'] as num).toDouble()};')
    ..writeln('}\n');
  for (final mode in ['light', 'dark']) {
    final c = _m(mark[mode]);
    final cls = 'RkMark${mode[0].toUpperCase()}${mode.substring(1)}';
    if (c['note'] != null) b.writeln('/// ${c['note']}');
    b.writeln('abstract final class $cls {');
    for (final part in ['book', 'strap', 'entries', 'seal']) {
      b.writeln('  static const $part = Color(${_argb(c[part] as String)});');
    }
    b.writeln('}\n');
  }
  return b.toString();
}

// ---------------------------------------------------------------- CSS

String _css(Map<String, dynamic> t) {
  final b = StringBuffer()
    ..writeln('/* GENERATED by scripts/gen_tokens.dart from ${_meta(t)}.')
    ..writeln(
      '   Do not edit — change design/tokens/tokens.json and re-run. CI fails on drift. */',
    )
    ..writeln();
  final color = _m(t['color']);
  String colorBlock(String mode) {
    final sb = StringBuffer();
    for (final e in _m(color[mode]).entries) {
      final role = (_m(e.value)['role'] as String);
      final flag = role.startsWith('PROPOSED') ? '   /* PROPOSED */' : '';
      sb.writeln('  --${e.key}: ${_m(e.value)['value']};$flag');
    }
    return sb.toString();
  }

  final typo = _m(t['typography']);
  final lh = _m(typo['lineHeight']);
  const cssScaleName = {
    'table-row': 'row',
  }; // keep the mockup variable names stable
  b
    ..writeln(':root {')
    ..writeln('  /* color — light */')
    ..write(colorBlock('light'))
    ..writeln()
    ..writeln('  /* type */')
    ..writeln(
      '  --font-ui: ${(_m(typo['family'])['ui'] as String).replaceAll("'", '"')};',
    );
  for (final e in _m(typo['scale']).entries) {
    final n = cssScaleName[e.key] ?? e.key;
    b.writeln(
      '  --fs-$n: ${_m(e.value)['size']}px; --fw-$n: ${_m(e.value)['weight']};',
    );
  }
  b.writeln('  --lh-tight: ${lh['tight']}; --lh-normal: ${lh['normal']};');

  final space = _m(t['space']);
  final unit = space['unit'] as int;
  b
    ..writeln()
    ..writeln('  /* space / radius / elevation */')
    ..writeln(
      (space['steps'] as List)
          .cast<int>()
          .map((s) => '  --sp-${s ~/ unit}: ${s}px;')
          .join('\n'),
    )
    ..writeln('  --row-min-h: ${space['rowMinHeight']}px;');
  final radius = _m(t['radius']);
  b
    ..writeln(
      '  --r-sm: ${radius['sm']}px; --r-md: ${radius['md']}px; --r-lg: ${radius['lg']}px;',
    )
    ..writeln(
      '  --rule-left: ${_m(radius['ruleLeft'])['width']}px solid var(--primary);',
    )
    ..writeln('  --shadow-soft: ${_m(t['elevation'])['shadow-soft']};');

  final motion = _m(t['motion']);
  final dur = _m(motion['duration']);
  final loader = _m(motion['loader']);
  b
    ..writeln()
    ..writeln('  /* motion */')
    ..writeln('  --ease-brand: ${motion['ease-brand']};')
    ..writeln('  --ease-entries: ${motion['ease-entries']};')
    ..writeln(
      dur.entries
          .map((e) => '  --dur-${e.key}: ${_ms(e.value as num)};')
          .join('\n'),
    )
    ..writeln(
      '  --loader-track-h: ${loader['track-height']}px; --loader-segment-w: ${((loader['segment-fraction'] as num) * 100).round()}%; --loader-sweep: ${_ms(loader['loop-sweep-ms'] as num)};',
    )
    ..writeln(
      '  --loader-appear-delay: ${_ms(loader['appear-delay-ms'] as num)}; --loader-escalate: ${_ms(loader['escalate-ms'] as num)};',
    )
    ..writeln(
      '  --splash-slow-start: ${_ms(_m(motion['splash'])['slow-start-threshold-ms'] as num)}; --shake-dur: ${_ms(_m(motion['mark-fail-shake'])['duration-ms'] as num)};',
    )
    ..writeln('}')
    ..writeln()
    ..writeln('[data-theme="dark"] {')
    ..write(colorBlock('dark'))
    ..writeln('}')
    ..writeln()
    ..write(_cssUtilities);
  return b.toString();
}

/// Non-negotiables encoded as utilities. Hand-authored here (not derivable from
/// JSON) but they reference variables only — never a literal value.
const _cssUtilities = r'''
/* Non-negotiables encoded as utilities */
body { background: var(--bg); color: var(--text); font-family: var(--font-ui);
       font-size: var(--fs-body); line-height: var(--lh-normal); }

.amount { font-variant-numeric: tabular-nums; font-weight: var(--fw-amount-row); }
.amount.hero { font-size: var(--fs-amount-hero); font-weight: var(--fw-amount-hero); }
.amount.credit { color: var(--credit); }   /* numerals only — never rows/cards */
.amount.debit  { color: var(--debit); }
/* Signs are a CONSUMER-surface device only (Home, day book, drill-downs).
   Professional surfaces (A/C statement Dr|Cr|Balance columns, trial balance,
   exports) show absolute values with a side tag and NO sign — 02 §2 / errata.
   Opt in explicitly with .signed; never auto-prefix. */
.amount.signed.credit::before { content: "+"; }
.amount.signed.debit::before  { content: "\2212"; } /* proper minus */

.hairline { border-bottom: 1px solid var(--hairline); }
.card { background: var(--surface); border-radius: var(--r-md);
        border-left: var(--rule-left); border-top-left-radius: 0;
        border-bottom-left-radius: 0; padding: var(--sp-4); }

:focus-visible { outline: 2px solid var(--focus); outline-offset: 2px; }

/* The loader is a RULE (11 §4.5). Never a spinner; never --primary/--accent. */
.loader { height: var(--loader-track-h); background: var(--loader-track); position: relative; overflow: hidden; }
.loader > .seg { position: absolute; inset: 0 auto 0 0; width: var(--loader-segment-w); background: var(--loader-segment);
                 animation: loader-sweep var(--loader-sweep) var(--ease-entries) infinite; }
.loader.determinate > .seg { animation: none; width: var(--progress, 0%); }
@keyframes loader-sweep { from { transform: translateX(-100%); } to { transform: translateX(333%); } }
.skeleton-row { display: flex; justify-content: space-between; align-items: center; min-height: var(--row-min-h, 56px); border-bottom: 1px solid var(--hairline); }
.skeleton-row > .label { height: 10px; border-radius: 3px; background: var(--skeleton-label); width: var(--w, 48%); }
.skeleton-row > .amount { height: 10px; border-radius: 3px; background: var(--skeleton-amount); width: 22%; }

@media (prefers-reduced-motion: reduce) {
  * { animation-duration: 0.01ms !important; transition-duration: 0.01ms !important; }
  .loader > .seg { animation: none; width: 100%; opacity: .25; } /* static track + the words do the work */
}
''';
