// GENERATED by scripts/gen_tokens.dart from tokens.json v0.1.0; docs/11-brand-guidelines.md §4 (v1.4).
// Do not edit — change design/tokens/tokens.json and re-run. CI fails on drift.
//
// UI code uses these tokens ONLY; a hex literal in a widget is review-blocking
// (CLAUDE.md § Layout). Never imported by core packages.
import 'package:flutter/material.dart';

/// Colours — light. Light and dark are full sets; the app never derives one from the other.
abstract final class RkColorsLight {
  /// app background — paper, never pure white
  static const bg = Color(0xFFF5F0E4);

  /// cards, sheets, raised rows
  static const surface = Color(0xFFFBF8F0);

  /// PROPOSED — recessed wells: avatar discs, keypad wells, summary strips (in canvas use since the 1 Sep fold)
  static const sunk = Color(0xFFEFE9DA);

  /// body text — ink, never pure black
  static const text = Color(0xFF1A1A18);

  /// secondary text, meta, captions (warm grey)
  static const textMuted = Color(0xFF6E6A5E);

  /// table rules, dividers — the ruled-column motif
  static const hairline = Color(0xFFE3DCCB);

  /// ink-indigo: headers, primary buttons, links. NEVER a value judgement
  static const primary = Color(0xFF2B3A67);

  /// text/icons on primary
  static const onPrimary = Color(0xFFF5F0E4);

  /// bahi red: one accent per screen max; also the seal
  static const accent = Color(0xFFC1502E);

  /// money in — NUMERALS ONLY, always with + and column position
  static const credit = Color(0xFF2F7A55);

  /// money out — NUMERALS ONLY, always with − and column position
  static const debit = Color(0xFFA83232);

  /// loader hairline (brand §4.5) — 2px, ink @14%
  static const loaderTrack = Color(0x241A1A18);

  /// loader ink segment — the surface's ink, never primary/accent
  static const loaderSegment = Color(0xFF1A1A18);

  /// skeleton label block (static, no shimmer)
  static const skeletonLabel = Color(0x171A1A18);

  /// skeleton amount block, right-aligned
  static const skeletonAmount = Color(0x211A1A18);

  /// PROPOSED — awaiting-approval state (amber/mustard, distinct from accent and debit)
  static const pending = Color(0xFF8F5F00);

  /// PROPOSED — locked periods, disabled dates, read-only (warm grey)
  static const locked = Color(0xFF8A857A);

  /// security-warning background (mismatch, recovery request)
  static const dangerSurface = Color(0xFFF6E3DD);

  /// PROPOSED — backdrop behind bottom sheets and covers
  static const scrim = Color(0x6B1A1A18);

  /// focus ring, 2px, offset 2px
  static const focus = Color(0xFF2B3A67);
}

/// Colours — dark. Light and dark are full sets; the app never derives one from the other.
abstract final class RkColorsDark {
  /// ink background (brand §4.3: dark mode required)
  static const bg = Color(0xFF1A1A18);

  /// raised on ink
  static const surface = Color(0xFF24231F);

  /// PROPOSED
  static const sunk = Color(0xFF1F1E1B);

  /// paper text
  static const text = Color(0xFFF5F0E4);
  static const textMuted = Color(0xFFA5A093);
  static const hairline = Color(0xFF3A382F);

  /// indigo lifted for contrast on ink
  static const primary = Color(0xFF93A5D6);
  static const onPrimary = Color(0xFF1A1A18);

  /// bahi red lifted
  static const accent = Color(0xFFD9754F);

  /// hue kept, lightness lifted (brand §4.3) — owner-ruled 4 Sep 2026 to the motion page value (ADR 2026-09-03d)
  static const credit = Color(0xFF4FA37A);

  /// hue kept, lightness lifted — owner-ruled 4 Sep 2026: motion-page hue, one step lighter than its #C96A6A so 16px amounts pass AA on surface (4.53:1) (ADR 2026-09-03d)
  static const debit = Color(0xFFCB6F6F);

  /// loader hairline on ink
  static const loaderTrack = Color(0x29F5F0E4);

  /// loader segment on ink — solid paper
  static const loaderSegment = Color(0xFFF5F0E4);
  static const skeletonLabel = Color(0x17F5F0E4);
  static const skeletonAmount = Color(0x24F5F0E4);

  /// PROPOSED
  static const pending = Color(0xFFD9A93F);

  /// PROPOSED
  static const locked = Color(0xFF7A756A);
  static const dangerSurface = Color(0xFF3A2723);

  /// PROPOSED
  static const scrim = Color(0x73000000);
  static const focus = Color(0xFF93A5D6);
}

/// Type scale — logical px at scale 1.0; layouts must survive OS font scale 200 % (07 §18).
/// One family across scripts (brand §4.4): Mukta = Latin+Devanagari, Mukta Mahee = Gurmukhi; Noto Sans fallback only
/// font-variant-numeric: tabular-nums on EVERY element containing an amount — global, non-negotiable (brand §4.4)
abstract final class RkType {
  static const family = 'Mukta';
  static const familyGurmukhi = 'MuktaMahee';
  static const familyFallback = 'NotoSans';
  static const lineHeightTight = 1.2;
  static const lineHeightNormal = 1.5;

  /// Amounts: ALWAYS tabular figures (11 §4.4).
  static const tabular = [FontFeature.tabularFigures()];

  /// deck/marketing may go to 56
  static const display = TextStyle(
    fontSize: 40,
    fontWeight: FontWeight.w600,
    height: 1.2,
  );
  static const page = TextStyle(
    fontSize: 28,
    fontWeight: FontWeight.w600,
    height: 1.2,
  );
  static const section = TextStyle(
    fontSize: 20,
    fontWeight: FontWeight.w500,
    height: 1.2,
  );
  static const body = TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w400,
    height: 1.5,
  );
  static const tableRow = TextStyle(
    fontSize: 14,
    fontWeight: FontWeight.w400,
    height: 1.5,
  );
  static const caption = TextStyle(
    fontSize: 12,
    fontWeight: FontWeight.w400,
    height: 1.5,
  );

  /// entry keypad amount; tabular
  static const amountHero = TextStyle(
    fontSize: 44,
    fontWeight: FontWeight.w600,
    fontFeatures: tabular,
  );

  /// amounts in lists/tables; tabular
  static const amountRow = TextStyle(
    fontSize: 16,
    fontWeight: FontWeight.w500,
    fontFeatures: tabular,
  );
}

/// 4pt grid; screen gutter 16; card padding 16; list row min-height 56
abstract final class RkSpace {
  static const s1 = 4.0;
  static const s2 = 8.0;
  static const s3 = 12.0;
  static const s4 = 16.0;
  static const s5 = 20.0;
  static const s6 = 24.0;
  static const s8 = 32.0;
  static const s10 = 40.0;
  static const s12 = 48.0;
  static const gutter = 16.0;
  static const cardPadding = 16.0;
  static const rowMinHeight = 56.0;
}

abstract final class RkRadius {
  static const sm = 4.0;
  static const md = 8.0;
  static const lg = 12.0;

  /// 3px left rule on cards/callouts — never rounded on that side (brand §4.1)
  static const ruleLeftWidth = 3.0;
}

/// hairlines over shadows — this is a paper product.
abstract final class RkMotion {
  static const easeBrand = Cubic(0.45, 0.0, 0.25, 1.0);
  static const easeEntries = Cubic(0.35, 0.0, 0.2, 1.0);
  static const xs = Duration(milliseconds: 120);
  static const s = Duration(milliseconds: 200);
  static const m = Duration(milliseconds: 300);
  static const l = Duration(milliseconds: 400);

  /// sealed→open per brand §4.2; plays ONLY on real unlock (splash multiplier applies only when the session is already open — a locked launch animates nothing); jump cut under prefers-reduced-motion
  static const markUnlockTotal = Duration(milliseconds: 860);
  static const markSplashMultiplier = 1.0;
  static const markBiometricMultiplier = 0.6;

  /// failed unlock: mark stays sealed, horizontal shake (brand §4.5)
  static const failShake = Duration(milliseconds: 240);
  static const failShakeAmplitudeUnits = 2.0;
  static const failShakeCycles = 3;

  /// the loader is a RULE (2px hairline + ink segment), never a spinner, never indigo/bahi; colours under color.*.loader-track / loader-segment; reduced motion = static track @25% ink + text; announce as live region (brand §4.5, ADR 2026-09-03d)
  /// Copy: {done} of {total} {things} {verbed} — counts, never percentages; indeterminate always carries a verb
  static const loaderTrackHeight = 2.0;
  static const loaderSegmentFraction = 0.3;
  static const loaderSweep = Duration(milliseconds: 1200);
  static const loaderAppearDelay = Duration(milliseconds: 200);
  static const loaderEscalate = Duration(milliseconds: 8000);

  /// true row pitch, zero layout shift on swap, no shimmer; colours under color.*.skeleton-label / skeleton-amount (brand §4.5)
  static const skeletonStatic = true;
  static const skeletonLabelWidthMin = 0.38;
  static const skeletonLabelWidthMax = 0.58;

  /// phase 1 (OS frame) and phase 2 (first app frame) pixel-identical; branches: locked = nothing · open session = mark m 1.0 once · unlock success = m 0.6 · fail = mark-fail-shake · slow start = loader rule + 'Opening your books.' (brand §4.5)
  static const splashSlowStart = Duration(milliseconds: 3000);
}

/// shape language = rules, columns, folds (brand §4.1); no filled blobs. Mark: embed the master SVG; never redraw the mark per screen.
abstract final class RkIcon {
  static const grid = 24.0;
  static const stroke = 2.0;
}

abstract final class RkMarkLight {
  static const book = Color(0xFF2B3A67);
  static const strap = Color(0xFFF5F0E4);
  static const entries = Color(0xFFF5F0E4);
  static const seal = Color(0xFFC1502E);
}

/// paper-book inverse (brand §4.2) — never a white knockout; the seal stays bahi red, not the lifted dark accent
abstract final class RkMarkDark {
  static const book = Color(0xFFF5F0E4);
  static const strap = Color(0xFF2B3A67);
  static const entries = Color(0xFF2B3A67);
  static const seal = Color(0xFFC1502E);
}
